

# tasks file for roles/osp-instance-delete
- hosts: workstation
  gather_facts: true
  roles:
  - name: osp-facts
  tasks:
  - name: Curl website
    command:
      cmd: "curl -s {% for host in groups['load_balancers'] %} http://{{ host }} {% endfor %}"
    register: result

  - name: Fail if 'Ansible has done its job' is not in the page content
    fail:
    when: "'Ansible has done its job' not in {{ result.stdout }}"
    tags:
      - osp.smoke
