---
# Initial, common, system setup steps

- name: enable sudo without tty for some ansible commands
  replace:
    path: /etc/sudoers
    regexp: '^Defaults\s*requiretty'
    replace: 'Defaults  !requiretty'
    backup: yes
  tags:
    - base-config

- name: enable repos
  template:
    src: repos_template.j2
    dest: /etc/yum.repos.d/internal.repo
    owner: root
    group: root
    mode: '0600'
  tags:
    - base-config
 
- name: install base tools and packages
  yum:
    name: "vim"
    state: present
  tags:
    - base-config


